#!/bin/sh
# Generate the list of kernel headers for Makefile.nbincludes.
# Exit immediately if any command fails.
#
# This script scans the architecture subdirectories under sys/ and
# records header files such as disklabel.h and ELF variants.  The
# resulting list is written to "headerlist".
#
# $NetBSD: mkheaderlist.sh,v 1.3 2016/02/23 11:43:04 skrll Exp $

set -e

mklist()
{
	echo "# \$211BSD\$"
	echo "#"
	echo '# do not edit; this file was automatically generated by:'
	echo '#	$211BSD: mkheaderlist.sh,v 1.3 2016/02/23 11:43:04 skrll Exp $' | sed -e 's/\$//g'
	echo
        cd ../sys/arch || {
                echo "Cannot find ../sys/arch" >&2
                exit 1
        }
        find . -name disklabel.h -o -name elf_machdep.h \
            -o -name ecoff_machdep.h -o -name xcoff_machdep.h | sort
}

LIST=headerlist
# Always recreate the list to avoid stale results.
rm -f "${LIST}"
mklist > "${LIST}"
